# Generated by Django 5.2.4 on 2025-07-23 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_userprofile_options_remove_userprofile_avatar_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="role",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="customuser",
            name="user_level",
            field=models.CharField(
                choices=[
                    ("super_admin", "Super Admin"),
                    ("sector_officer", "SECTOR EXECUTIVE OFFICER"),
                    ("cell_officer", "Cell Executive Officer"),
                    ("citizen", "citizen"),
                ],
                default="citizen",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="national_id",
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
