# Generated by Django 5.2.4 on 2025-07-23 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sector", "0001_initial"),
        ("users", "0003_remove_customuser_created_at_remove_customuser_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="assigned_sector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="sector.adminsector",
            ),
        ),
    ]
