# Generated by Django 5.2.4 on 2025-07-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umuganda", "0005_feedback"),
    ]

    operations = [
        migrations.AddField(
            model_name="fine",
            name="claim",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="fine",
            name="claim_has_been_approved",
            field=models.BooleanField(default=False),
        ),
    ]
