# Generated by Django 5.2.4 on 2025-07-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umuganda", "0006_fine_claim_fine_claim_has_been_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="fine",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("MoMo", "Mobile Money"), ("Airtel", "Airtel Money")],
                max_length=50,
                null=True,
            ),
        ),
    ]
