# Generated by Django 5.2.4 on 2025-07-24 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umuganda", "0007_fine_payment_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="fine",
            name="payment_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
