# Generated by Django 5.2.4 on 2025-07-27 10:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umuganda", "0008_fine_payment_id"),
        ("users", "0004_userprofile_assigned_sector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="umugandasession",
            name="cell",
        ),
        migrations.RemoveField(
            model_name="umugandasession",
            name="description",
        ),
        migrations.RemoveField(
            model_name="umugandasession",
            name="fines_policy",
        ),
        migrations.RemoveField(
            model_name="umugandasession",
            name="tools_needed",
        ),
        migrations.RemoveField(
            model_name="umugandasession",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="umugandasession",
            name="updated_by_cell_admin",
        ),
        migrations.RemoveField(
            model_name="umugandasession",
            name="village",
        ),
        migrations.CreateModel(
            name="CellUmugandaSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tools_needed", models.TextField(blank=True, null=True)),
                ("fines_policy", models.PositiveIntegerField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_umuganda_sessions",
                        to="users.cell",
                    ),
                ),
                (
                    "sector_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_sessions",
                        to="umuganda.umugandasession",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.village",
                    ),
                ),
            ],
            options={
                "unique_together": {("sector_session", "cell")},
            },
        ),
    ]
