# Generated by Django 5.2.4 on 2025-07-27 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umuganda", "0010_cellumugandasession_other_details"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendances",
                to="umuganda.cellumugandasession",
            ),
        ),
    ]
