# Generated by Django 5.2.4 on 2025-07-27 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("umuganda", "0011_alter_attendance_session"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fine",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fines",
                to="umuganda.cellumugandasession",
            ),
        ),
    ]
