# Generated by Django 5.2.4 on 2025-07-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("payment", "0001_initial"),
        ("umuganda", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymenttransaction",
            name="fine",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="transaction",
                to="umuganda.fine",
            ),
        ),
        migrations.AddField(
            model_name="paymenttransaction",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="payment.paymentprovider",
            ),
        ),
    ]
