# Generated by Django 5.2.4 on 2025-07-23 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sector", "0001_initial"),
        ("users", "0003_remove_customuser_created_at_remove_customuser_role_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminActionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=255)),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("admin_created", "Admin Created"),
                            ("user_suspended", "User Suspended"),
                            ("profile_updated", "Profile Updated"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("otp_requested", "OTP Requested"),
                            ("otp_verified", "OTP Verified"),
                            ("password_reset_requested", "Password Reset Requested"),
                            ("password_reset_successful", "Password Reset Successful"),
                            ("sector_created", "Sector Created"),
                            ("umuganda_created", "Umuganda Activity Created"),
                            ("umuganda_edited", "Umuganda Activity Edited"),
                            ("umuganda_deleted", "Umuganda Activity Deleted"),
                            ("assignment_made", "Officer Assigned to Umuganda"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Category of action performed",
                        max_length=50,
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        help_text="Optional extra context (e.g. old/new values)",
                        null=True,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.ForeignKey(
                        limit_choices_to={"user_level__startswith": "admin_"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        help_text="If the action was about another user",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="actions_taken_on",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminHierarchy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        help_text="The admin who added this admin",
                        limit_choices_to={
                            "user_level__in": ["super_admin", "sector_officer"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admins_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "admin",
                    models.OneToOneField(
                        help_text="The admin who was added",
                        limit_choices_to={
                            "user_level__in": ["sector_officer", "cell_officer"]
                        },
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="added_by_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="sectorAdminMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sector_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_members",
                        to="sector.adminsector",
                    ),
                ),
            ],
            options={
                "verbose_name": "sector Admin Membership",
                "verbose_name_plural": "sector Admin Memberships",
            },
        ),
        migrations.CreateModel(
            name="UmugandaAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about the assignment",
                        null=True,
                    ),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Higher-level admin who made or edited the assignment",
                        limit_choices_to={
                            "user_level__in": [
                                "sector_officer",
                                "district_admin",
                                "project_superadmin",
                            ]
                        },
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="umuganda_assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cell",
                    models.ForeignKey(
                        help_text="The cell to which this assignment applies",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="umuganda_assignments",
                        to="users.cell",
                    ),
                ),
                (
                    "cell_officer",
                    models.ForeignKey(
                        help_text="Cell officer assigned to coordinate Umuganda",
                        limit_choices_to={"user_level": "cell_officer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="umuganda_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Umuganda Assignment",
                "verbose_name_plural": "Umuganda Assignments",
                "unique_together": {("cell_officer", "cell")},
            },
        ),
    ]
