# Generated by Django 5.2.4 on 2025-07-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admn", "0001_initial"),
        ("sector", "0002_alter_adminsector_sector_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sectoradminmembership",
            options={
                "verbose_name": "Sector Admin Membership",
                "verbose_name_plural": "Sector Admin Memberships",
            },
        ),
        migrations.AlterField(
            model_name="sectoradminmembership",
            name="sector",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_membership",
                to="sector.adminsector",
            ),
        ),
    ]
