# Generated by Django 5.2.4 on 2025-07-23 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admn", "0003_sectoradminmembership_unique_admin_per_sector_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="sectoradminmembership",
            name="unique_admin_per_sector",
        ),
        migrations.RemoveConstraint(
            model_name="sectoradminmembership",
            name="unique_sector_per_admin",
        ),
    ]
