# Generated by Django 5.2.4 on 2025-07-23 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admn", "0004_remove_sectoradminmembership_unique_admin_per_sector_and_more"),
        ("sector", "0002_alter_adminsector_sector_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="sectoradminmembership",
            constraint=models.UniqueConstraint(
                fields=("admin",), name="unique_admin_per_sector"
            ),
        ),
        migrations.AddConstraint(
            model_name="sectoradminmembership",
            constraint=models.UniqueConstraint(
                fields=("sector",), name="unique_sector_per_admin"
            ),
        ),
    ]
