# Generated by Django 5.2.4 on 2025-07-23 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admn", "0005_sectoradminmembership_unique_admin_per_sector_and_more"),
        ("users", "0004_userprofile_assigned_sector"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CellAdminMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin",
                    models.OneToOneField(
                        help_text="User assigned as the cell officer",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cell_membership",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cell",
                    models.OneToOneField(
                        help_text="Cell this admin is responsible for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_membership",
                        to="users.cell",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell Admin Membership",
                "verbose_name_plural": "Cell Admin Memberships",
                "ordering": [
                    "cell__sector__district__name",
                    "cell__sector__name",
                    "cell__name",
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("admin",), name="unique_admin_per_cell"
                    ),
                    models.UniqueConstraint(
                        fields=("cell",), name="unique_cell_per_admin"
                    ),
                ],
            },
        ),
    ]
