# Generated by Django 5.2.4 on 2025-07-23 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admn", "0006_celladminmembership"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="celladminmembership",
            name="admin",
            field=models.OneToOneField(
                help_text="User assigned as the cell officer",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cell_memberships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
