# Generated by Django 5.2.4 on 2025-07-23 07:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminSector",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "district",
                    models.ForeignKey(
                        help_text="District to which this sector belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_sectors",
                        to="users.district",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        help_text="Province to which this sector belongs",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_sectors",
                        to="users.province",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        help_text="Unique sector reference (must match national hierarchy)",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="users.sector",
                    ),
                ),
            ],
            options={
                "verbose_name": "Administrative Sector",
                "verbose_name_plural": "Administrative Sectors",
                "ordering": ["province__name", "district__name", "sector__name"],
            },
        ),
        migrations.CreateModel(
            name="sectorAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cell",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.cell",
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.district",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.province",
                    ),
                ),
                (
                    "sector",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.sector",
                    ),
                ),
                (
                    "village",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.village",
                    ),
                ),
            ],
            options={
                "verbose_name": "sector Assignment",
                "verbose_name_plural": "sector Assignments",
                "unique_together": {("sector",)},
            },
        ),
    ]
