# Generated by Django 5.2.4 on 2025-07-23 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sector", "0001_initial"),
        ("users", "0004_userprofile_assigned_sector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminsector",
            name="sector",
            field=models.ForeignKey(
                help_text="Unique sector reference (must match national hierarchy)",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="admin_sectors",
                to="users.sector",
            ),
        ),
        migrations.AddConstraint(
            model_name="adminsector",
            constraint=models.UniqueConstraint(
                fields=("province", "district", "sector"),
                name="unique_admin_sector_combination",
            ),
        ),
    ]
